# Site
repository: quinngoldstein/quinngoldstein.github.io
# Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/letterq.png
# Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Quinn Goldstein
title: Computer Science Major at Seattle University
email: quinngoldsteinedu@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  quinngoldstein
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: quinn-goldstein
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  My name is Quinn Goldstein. I am a computer science major at [Seattle University](https://www.seattleu.edu/scieng/computer-science/).
  I expect to graduate in June 2023. Please feel free to reach out at my email above.

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: Seattle University
        sub_title: B.S. in Computer Science
        caption: September 2019 - June 2023
        description: | # this will include new lines to allow paragraphs
          I am a member of Seattle U's Hui O Nani Hawaii Club and its ACM Club. In my course work,
          I have studied data structures and object-oriented programming and design. I have also taken
          courses on databases and am currently taking courses on learning programming languages and a
          course on machine learning.
          I have primarily worked with C++ and C# in these courses. I also have some experience with
          Python and have worked with machine learning models using Python's scikit module.
          I plan to complete my coursework with machine learning by summer 2022.
          My cumulative GPA is 3.831.
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: Seattle University
        sub_title: Student Grader
        caption: |
          March 2023 - June 2023,
          Seattle, WA
        description: | # this will include new lines to allow paragraphs
          In my final quarter at Seattle University, I took on a position of being a grader for CPSC 3200,
          the university's object-oriented programming course. This is a junior level course. I graded
          student programs based on their design of classes and ability to execute as outlined by the
          professor. These programs were written in C++ and C#. Working with a group of four other graders,
          we also considered adjustments to the professor's rubrics if we saw change necessary.
      - layout: left
        title: Expedia Group
        sub_title: UX Engineering Intern
        caption: |
          June 2022 - August 2022,
          Seattle, WA
        description: | # this will include new lines to allow paragraphs
          Following my junior year, I interned with Expedia Group as a software development engineering
          intern and worked with a team of front-end and user experience engineers to support other teams.
          In my experience, I worked with React, TypeScript, and a small amount of GraphQL. I collaborated
          with an intern on another team to fix front-end bugs on various components in React. These bugs
          mostly involved accessibility issues like screen readers failing or language errors. Throughout
          my ten weeks in the program, I worked on a research project to investigate version updates to the
          company's codebase and consider alternatives to company norms.
      - layout: left
        title: The Children's House
        sub_title: Afternoon Assistant
        caption: | 
          August 2020 - September 2021,
          Pearl City, HI
        description: | # this will include new lines to allow paragraphs
          I worked at a school during the COVID-19 pandemic and was able to give back to my community
          as I attended this school in my youth. I conducted daily sanitization of high-touch
          areas like playgrounds and eating areas. I also helped to direct traffic during high-volume
          times like pickup and dropoff for students as well as help with projects around campus
          like plant tending and classroom setup for teachers.
      - layout: left
        title: Honolulu Star-Advertiser
        sub_title: Special to the Star-Advertiser
        caption: |
          October 2019 - March 2020,
          Honolulu, HI, remote
        description: |
          I worked with the head local newspaper to compile statistics from college sports on a weekly basis.
          I conducted this individual work remotely and met deadlines for my supervisor.
          While I mostly wrote weekly short sections, I was able to write my own article after conducting
          an interview with an athlete. This article is available
          [here](https://www.staradvertiser.com/2019/11/13/sports/hawaii-grown/hawaii-grown-hawaii-girls-chase-college-cup/).
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Seattle U ACM Hacking War Chess
        sub_title: Variation on classic chess
        additional_links:
          - title: GitHub page for project
            icon: fab fa-github
            url: https://github.com/quinngoldstein/WarChess
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title:  GitHub page for project
        #     icon: fab fa-github
        #     url: https://github.com/quinngoldstein/WarChess
        #   - title:  GitHub page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        caption: >
          January 2021
        description: | # this will include new lines to allow paragraphs
          My group was challenged to create a variation of a board game for
          the spring 2021 hacking event with Seattle University's ACM.
          We used Java to develop War Chess, a variation on chess with landscapes on a
          larger board. I handled some of the logic design for the pieces as
          well as basic asset design for the UI.
      - layout: left
        title: Resume Website
        # link: https://github.com/quinngoldstein/quinngoldstein.github.io
        # link_text: GitHub Repository
        additional_links:
          - title: GitHub page for project
            icon: fab fa-github
            url: https://github.com/quinngoldstein/quinngoldstein.github.io
        description: |
          Used GitHub and open source code to create resume website with
          HTML, CSS.
      - layout: left
        title: Scorigami Calculator
        sub_title: Calculator for NFL scores
        # link: https://github.com/quinngoldstein/ScorigamiCalculator
        # link_text: GitHub Repository
        additional_links:
          - title: GitHub page for project
            icon: fab fa-github
            url: https://github.com/quinngoldstein/ScorigamiCalculator
        caption: >
          November 2021
        description: |
          This Python application is a calculator to calculate what kind 
          of scoring would be necessary or NFL scoring since American football 
          uses an odd scoring system. This was inspired by Scorigami, which you 
          can check out [here](https://nflscorigami.com/), or reach out to me!
          The concept of Scorigami is something I am very interested in, 
          along with other sport statistics.
      - layout: left
        title: Movie Database Application
        sub_title: Database for movie information
        caption: >
          January - March 2022
        description: |
          Working with a partner for a database class, we developed a database using MySQL and
          an application for the database that allows users to search for movies
          on specific streaming services. I came up with this idea after having the
          recurring issue of not knowing what to watch on Netflix, Hulu, and other
          streaming sites, so I hoped to remedy the problem by designing this app
          for a course at Seattle University. For the web app, we used PHP, HTML, 
          and CSS to design the webpage and add some base functionality for the project. 
          The web application is no longer active on the university server, but I
          have the source code for future reference.
      - layout: left
        title: Machine Learning Project
        sub_title: Prediction for housing data in King County, WA
        additional_links:
          - title: GitHub page for project
            icon: fab fa-github
            url: https://github.com/quinngoldstein/CPSC4310-MLP
        caption: >
          April - June 2022
        description: |
          With a partner, we created a model for machine learning to predict housing prices
          of homes in King County, Washington. Using a dataset on home prices in
          Washington's King County, we trained a machine learning model to predict whether the
          price of a given home would be above or below a price threshold. We used various ML
          algorithms like k-nearest neighbor and the random forest classifier. This was done
          using Python in Jupyter Notebook and various libraries like pandas, numpy, scikit,
          and tensorflow. The GitHub repository linked contains notebooks of training the model
          and the analyses my partner and I completed.
      - layout: left
        title: UX Design Project
        sub_title: Study room reservations application mockup
        additional_links:
          - title: Figma page
            icon: fab fa-figma
            url: https://www.figma.com/proto/5Kl0lbRF8aWW8iSYR6kSdZ/TP8%3A-High-fidelity-prototype?node-id=115-973&starting-point-node-id=123%3A1047
        caption: >
          September - December 2022
        description: |
          Working in a group of four, my team used Figma to develop a prototype of a mobile app
          for Seattle University students to reserve study rooms on campus. The idea came about
          when one of my team members wanted to study in the library but found that no rooms were
          open. We designed the application interface from the ground up, down to the fonts and
          color palette. I enjoyed working with Figma and liked learning about the design process
          needed before a product goes to software engineers. The link on the left takes you to
          the interactive prototype of this application via Figma. 
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      The primary languages I have used in my education are **C++, C# and Python**. I also have some
      experience with **Figma** from my coursework. In my internship, I have worked with
      **TypeScript, HTML, and CSS/SASS in React**. I am comfortable with the
      **Microsoft Office** suite as well as the **Google applications**. In the workplace, I have used
      both Slack and Microsoft Teams for collaboration. I am a **quick learner** that can adapt to any
      situation and will rise to a challenge rather than back away from one. Other technical strengths
      of mine are my **math ability** and my **strong understanding of logic**. I consider myself above
      average at **technical writing** and pride myself on being an **effective communicator**.
  - title: More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I am an avid movie watcher and have watched countless movies during the pandemic. You can see some of
      my favorite films at my [Letterboxd](https://letterboxd.com/quinngold/). I also enjoy watching TV shows, 
      with some of my favorites including Jeopardy!, Seinfeld, and Twin Peaks. I am also a huge sports fan
      and enjoy watching all kinds of sports. In my free time, I like to play video games with friends and
      find good eateries around me. You can also find me always listening to music, and I enjoy listening
      to almost any genre.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]

theme: jekyll-theme-minimal