# Site
repository: quinngoldstein/quinngoldstein.github.io
# Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Quinn Goldstein
title: Computer Science Major at Seattle University
email: quinngoldsteinedu@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  quinngoldstein
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: quinn-goldstein
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profilepic.jpeg
about_content: | # this will include new lines to allow paragraphs
  My name is Quinn Goldstein. I am a computer science major at [Seattle University](https://www.seattleu.edu/scieng/computer-science/).
  I expect to graduate in June 2023. Please feel free to reach out to me at my email above.

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: Seattle University
        sub_title: B.S. in Computer Science
        caption: September 2019 - June 2023
        description: | # this will include new lines to allow paragraphs
          I am a member of Seattle U's Hui O Nani Hawaii Club and its ACM Club. In my course work,
          I have studied data structures and object-oriented programming and design.
          I have primarily worked with C++ and C# in these courses.
          I plan to have coursework on databases and algorithms by summer 2022.
          My cumulative GPA is 3.82.
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
    - layout: right
        title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Seattle U ACM Hacking War Chess
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        caption: >
          Variation on classic chess
        description: | # this will include new lines to allow paragraphs
          My group was challenged to create a variation of a board game for
          the spring 2021 hacking event with Seattle University's ACM.
          We used Java to develop War Chess, a variation on chess with landscapes on a
          larger board. I handled some of the logic design for the pieces as
          well as basic asset design for the UI.
      - layout: left
        title: Resume Website
        description: |
          Used Github and open sourced code to create resume website with
          HTML, CSS.
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      The primary languages I have used in my education are **C++ and C#**. I have some experience
      with **Python** after self-teaching. I am comfortable with the **Microsoft Office** applications
      as well as the **Google applications**. I am a **quick learner** that can adapt to any situation
      and will rise to a challenge rather than back away from one. Some of my technical strengths are
      my **math ability** and my **strong understanding of logic**.
  - title: More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I am an avid movie watcher and have watched countless movies during the pandemic. You can see some of
      my favorite films at my [Letterboxd](https://letterboxd.com/quinngold/). I am also a huge sports fan
      and enjoy watching all kinds of sports. In my free time, I like to play video games with friends and
      find good eateries around me.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]

theme: jekyll-theme-minimal